import numpy as np
import trimesh
from grasp import Contact, Grasp, Pose
from scipy.spatial.transform import Rotation as R


class GraspSampler:
    def __init__(self, mesh, gripper, mu):
        self.mesh = mesh
        self.gripper = gripper
        self.mu = mu

        # Initialize collision manager for the mesh
        self.collision_manager = trimesh.collision.CollisionManager()
        self.collision_manager.add_object("mesh", self.mesh)
        self.collision_manager.add_object("floor", self._make_floor())
        self.collision_manager.add_object(
            "left_finger", self.gripper.box_finger_left.mesh
        )
        self.collision_manager.add_object(
            "right_finger", self.gripper.box_finger_right.mesh
        )

    def _make_floor(self, epsilon=1e-4):
        plane = trimesh.Trimesh(
            vertices=[
                [-1, -1, -epsilon],
                [1, -1, -epsilon],
                [1, 1, -epsilon],
                [-1, 1, -epsilon],
            ],
            faces=[[0, 1, 2], [0, 2, 3]],
        )
        return plane

    def sample(self, n_samples, debug=False):
        grasps = self.sample_antipodal_points(n_samples)
        valid_grasps = []
        print(f"Sampled {len(grasps)} antipodal grasps, checking for collisions...")
        for grasp in grasps:
            poses = self.sample_poses(grasp.c1, grasp.c2)
            for pose in poses:
                if debug:
                    self.visualize_grasp(Grasp(pose, grasp.width, grasp.c1, grasp.c2))
                if not self.collision_check(pose.se3(), grasp.width):
                    valid_grasps.append(Grasp(pose, grasp.width, grasp.c1, grasp.c2))
                    break  # No need to check other poses for this grasp

        print(f"{len(valid_grasps)} valid grasps found after collision checking.")
        return valid_grasps

    def sample_antipodal_points(self, n_samples, eps=1e-3):
        # Sample points + face ids from the mesh
        pts, face_ids = self.mesh.sample(n_samples, return_index=True)
        mask = pts[:, 2] > 0.005  # Filter out points that are too close to the floor
        pts = pts[mask]
        face_ids = face_ids[mask]
        n1 = self.mesh.face_normals[face_ids]

        intersector = trimesh.ray.ray_pyembree.RayMeshIntersector(self.mesh)

        cos_theta = 1.0 / np.sqrt(1.0 + self.mu * self.mu)

        grasps = []
        for p, n in zip(pts, n1):
            d = -n  # direction shoots inward along negative normal
            origins = (p + eps * d).reshape(1, 3)
            directions = d.reshape(1, 3)

            locations, index_ray, index_tri = intersector.intersects_location(
                origins, directions, multiple_hits=True
            )

            if len(locations) == 0:
                continue

            for q in locations[::2]:  # Check every other hit
                q = locations[0]
                width = np.linalg.norm(q - p)
                if width < self.gripper.min_width or width > self.gripper.max_width:
                    continue

                m = self.mesh.face_normals[face_ids[0]]
                x = (q - p) / width
                # Check if the angle between the normal and the approach vector is within the friction cone
                if np.dot(m, -x) >= cos_theta:
                    c1 = Contact(pos=p, normal=n, mu=self.mu)
                    c2 = Contact(pos=q, normal=x, mu=self.mu)
                    grasps.append(Grasp(None, width, c1, c2))

        return grasps

    def collision_check(self, tf, width, eps=1e-3):
        # Open the gripper to the specified width, then apply the grasp pose
        half = width / 2 + self.gripper.box_finger_left.depth / 2 + eps
        left_offset = trimesh.transformations.translation_matrix([-half, 0, 0])
        right_offset = trimesh.transformations.translation_matrix([half, 0, 0])

        self.collision_manager.set_transform("left_finger", tf @ left_offset)
        self.collision_manager.set_transform("right_finger", tf @ right_offset)

        collision = self.collision_manager.in_collision_internal()
        return collision

    def sample_poses(self, c1, c2, k=12):
        """Sample k gripper poses by rotating around the closing axis.

        The closing axis (X) is fixed as the unit vector from c1 to c2.
        k poses are generated by rotating the approach direction (Y/Z plane)
        evenly around X.
        """
        mid = 0.5 * (c1.pos + c2.pos)
        width = np.linalg.norm(c2.pos - c1.pos)

        # Closing axis — fingers open along X
        x = (c2.pos - c1.pos) / width

        # Build an arbitrary orthonormal base perpendicular to x
        v = np.array([1.0, 0.0, 0.0]) if abs(x[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        y0 = np.cross(v, x)
        y0 /= np.linalg.norm(y0)
        z0 = np.cross(x, y0)

        poses = []
        for theta in np.linspace(0, 2 * np.pi, k, endpoint=False):
            y = np.cos(theta) * y0 + np.sin(theta) * z0
            z = -np.sin(theta) * y0 + np.cos(theta) * z0
            rot = np.column_stack([x, y, z])  # columns are basis vectors
            quat = R.from_matrix(rot).as_quat()
            poses.append(Pose(pos=mid - z * self.gripper.base_to_fingertip, quat=quat))

        return poses

    def visualize_grasp(self, grasp, eps=1e-3, viewer="gl"):
        scene = trimesh.Scene()
        ax = trimesh.creation.axis(
            origin_size=0.0025, axis_radius=0.0025, axis_length=0.1
        )
        scene.add_geometry(ax)
        scene.add_geometry(self.mesh)

        if grasp.pose is not None:
            ax = trimesh.creation.axis(
                origin_size=0.002, axis_radius=0.002, axis_length=0.04
            )
            scene.add_geometry(ax, transform=grasp.pose.se3())

        # Visualize the gripper fingers as boxes
        half = grasp.width / 2 + self.gripper.box_finger_left.depth / 2 + eps
        left_offset = trimesh.transformations.translation_matrix([-half, 0, 0])
        right_offset = trimesh.transformations.translation_matrix([half, 0, 0])

        tf = grasp.pose.se3()
        self.gripper.box_finger_left.mesh.visual.face_colors = [64, 255, 128, 128]
        self.gripper.box_finger_right.mesh.visual.face_colors = [64, 255, 128, 128]
        scene.add_geometry(
            self.gripper.box_finger_left.mesh, transform=tf @ left_offset
        )
        scene.add_geometry(
            self.gripper.box_finger_right.mesh, transform=tf @ right_offset
        )

        # Visualize contact points
        c1_sphere = trimesh.creation.uv_sphere(radius=0.0025)
        c1_sphere.visual.face_colors = [255, 0, 0, 255]
        scene.add_geometry(
            c1_sphere,
            transform=trimesh.transformations.translation_matrix(grasp.c1.pos),
        )

        c2_sphere = trimesh.creation.uv_sphere(radius=0.0025)
        c2_sphere.visual.face_colors = [255, 0, 0, 255]
        scene.add_geometry(
            c2_sphere,
            transform=trimesh.transformations.translation_matrix(grasp.c2.pos),
        )

        scene.show(viewer=viewer)
