import numpy as np
import trimesh
from grasp import Contact, Grasp, Pose
from scipy.spatial.transform import Rotation as R


class GraspSampler:
    def __init__(self, mesh, gripper, mu, seed=42):
        self.mesh = mesh
        self.gripper = gripper
        self.mu = mu

        self.seed = seed
        self.rng = np.random.default_rng(seed)

        # Initialize collision manager for the mesh
        self.collision_manager = trimesh.collision.CollisionManager()
        self.collision_manager.add_object("mesh", self.mesh)
        self.collision_manager.add_object("floor", self._make_floor())
        self.collision_manager.add_object(
            "left_finger", self.gripper.box_finger_left.mesh
        )
        self.collision_manager.add_object(
            "right_finger", self.gripper.box_finger_right.mesh
        )
        self.collision_manager.add_object(
            "cylinder_body", self.gripper.cylinder_body.mesh
        )

    def _make_floor(self, epsilon=1e-4):
        plane = trimesh.Trimesh(
            vertices=[
                [-1, -1, -epsilon],
                [1, -1, -epsilon],
                [1, 1, -epsilon],
                [-1, 1, -epsilon],
            ],
            faces=[[0, 1, 2], [0, 2, 3]],
        )
        return plane

    def sample(self, n_samples, debug=False):
        grasps = self.sample_antipodal_points(n_samples, debug=debug)
        valid_grasps = []
        print(f"Sampled {len(grasps)} antipodal grasps, checking for collisions...")
        for grasp in grasps:
            poses = self.sample_poses(grasp.c1, grasp.c2, k=12)
            for pose in poses:
                if debug:
                    self.visualize_grasp(Grasp(pose, grasp.width, grasp.c1, grasp.c2))
                if not self.collision_check(pose.se3(), grasp.width):
                    valid_grasps.append(Grasp(pose, grasp.width, grasp.c1, grasp.c2))
                    break  # No need to check other poses for this grasp

        print(f"{len(valid_grasps)} valid grasps found after collision checking.")
        return valid_grasps

    def sample_antipodal_points(self, n_samples, eps=1e-4, debug=False):
        # Sample points + face ids from the mesh
        pts, face_ids = self.mesh.sample(n_samples, return_index=True)
        mask = pts[:, 2] > 0.01  # Filter out points that are too close to the floor
        pts = pts[mask]
        face_ids = face_ids[mask]
        n1 = self.mesh.face_normals[face_ids]

        directions = -n1  # rays shoot inward along negative normal
        origins = pts + eps * directions

        intersector = trimesh.ray.ray_triangle.RayMeshIntersector(self.mesh)
        locs, index_ray, index_tri = intersector.intersects_location(
            origins, directions, multiple_hits=True
        )

        cos_theta = 1.0 / np.sqrt(1.0 + self.mu * self.mu)
        grasps = []

        for idx in np.unique(index_ray):
            mask = index_ray == idx
            qs = locs[mask][::2]  # Check every other hit
            tris = index_tri[mask][::2]

            p, n = pts[idx], n1[idx]
            dists = np.linalg.norm(qs - p, axis=1)
            ms = self.mesh.face_normals[tris]

            disp = (qs - p) / dists[:, None]
            inner_product = np.einsum("ij,ij->i", ms, disp)
            valid = (
                (dists >= self.gripper.min_width)
                & (dists <= self.gripper.max_width)
                & (inner_product >= cos_theta)
            )
            for q, d, m in zip(qs[valid], dists[valid], ms[valid]):
                grasps.append(
                    Grasp(
                        None,
                        d,
                        Contact(pos=p, normal=n, mu=self.mu),
                        Contact(pos=q, normal=m, mu=self.mu),
                    )
                )

        return grasps

    def collision_check(self, tf, width, eps=1e-3):
        # Open the gripper to the specified width, then apply the grasp pose
        half = width / 2 + self.gripper.box_finger_left.depth / 2 + eps
        left_offset = trimesh.transformations.translation_matrix([-half, 0, 0])
        right_offset = trimesh.transformations.translation_matrix([half, 0, 0])

        self.collision_manager.set_transform("left_finger", tf @ left_offset)
        self.collision_manager.set_transform("right_finger", tf @ right_offset)
        self.collision_manager.set_transform("cylinder_body", tf)

        collision = self.collision_manager.in_collision_internal()
        return collision

    def sample_poses(self, c1, c2, k=12):
        """Sample k gripper poses by rotating around the closing axis.

        The closing axis (X) is fixed as the unit vector from c1 to c2.
        k poses are generated by rotating the approach direction (Y/Z plane)
        evenly around X.
        """
        mid = 0.5 * (c1.pos + c2.pos)
        width = np.linalg.norm(c2.pos - c1.pos)

        # Closing axis — fingers open along X
        x = (c2.pos - c1.pos) / width

        # Build an arbitrary orthonormal base perpendicular to x
        v = np.array([1.0, 0.0, 0.0]) if abs(x[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        y0 = np.cross(v, x)
        y0 /= np.linalg.norm(y0)
        z0 = np.cross(x, y0)

        poses = []
        for theta in np.linspace(0, 2 * np.pi, k, endpoint=False):
            y = np.cos(theta) * y0 + np.sin(theta) * z0
            z = -np.sin(theta) * y0 + np.cos(theta) * z0
            rot = np.column_stack([x, y, z])  # columns are basis vectors
            quat = R.from_matrix(rot).as_quat()
            poses.append(Pose(pos=mid - z * self.gripper.base_to_fingertip, quat=quat))

        return poses

    def visualize_grasp(self, grasp, eps=1e-3, viewer="gl"):
        scene = trimesh.Scene()
        ax = trimesh.creation.axis(
            origin_size=0.0025, axis_radius=0.0025, axis_length=0.1
        )
        scene.add_geometry(ax)
        scene.add_geometry(self.mesh)

        if grasp.pose is not None:
            ax = trimesh.creation.axis(
                origin_size=0.002, axis_radius=0.002, axis_length=0.04
            )
            scene.add_geometry(ax, transform=grasp.pose.se3())

        # Visualize the gripper fingers as boxes
        half = grasp.width / 2 + self.gripper.box_finger_left.depth / 2 + eps
        left_offset = trimesh.transformations.translation_matrix([-half, 0, 0])
        right_offset = trimesh.transformations.translation_matrix([half, 0, 0])

        tf = grasp.pose.se3()
        scene.add_geometry(
            self.gripper.box_finger_left.mesh, transform=tf @ left_offset
        )
        scene.add_geometry(
            self.gripper.box_finger_right.mesh, transform=tf @ right_offset
        )
        scene.add_geometry(self.gripper.cylinder_body.mesh, transform=tf)

        # Visualize contact points
        c1_sphere = trimesh.creation.uv_sphere(radius=0.0025)
        c1_sphere.visual.face_colors = [255, 0, 0, 255]
        scene.add_geometry(
            c1_sphere,
            transform=trimesh.transformations.translation_matrix(grasp.c1.pos),
        )

        c2_sphere = trimesh.creation.uv_sphere(radius=0.0025)
        c2_sphere.visual.face_colors = [255, 0, 0, 255]
        scene.add_geometry(
            c2_sphere,
            transform=trimesh.transformations.translation_matrix(grasp.c2.pos),
        )

        scene.show(viewer=viewer)
